### PR TITLE
update jekyll-timeago data

### PR DESCRIPTION
**Pull request by markets**

### CODE REVIEW

**Comment by markets** [comment]
Hi @geraldb I was just going through that page and I saw this. Thanks for the `planetjekyll` ecosystem :ok_hand: 

I also found some outdated data in https://planetjekyll.github.io/plugins/top should I submit a PR there?

**Comment by geraldb** [comment]
@markets  Thanks for the update. The files in /o (for output) get generated (auto-updated) - so any changes will get overwritten with the next update.

**Comment by geraldb** [comment]
@markets The top page also gets "auto-generated" only the build script do NOT run (unfortunately) automatically. Thus, the long (forever) delay. The build scripts are open source here <https://github.com/yorobot/planetjekyll>.

**Comment by markets** [comment]
@geraldb ok! didn't know about how this data is updated and I neither noticed the "auto-generated" sentence. 

So, perhaps it's worth to run a manual update? most of data are actually outdated.

Would be amazing to run those scripts as a part of a CI :ok_hand:

**Comment by geraldb** [comment]
> should I submit a PR there?

@markets   Not sure if that's a stretch - you're more than welcome to join the planet jekyll org (just let me know and I send along the invite via github) and help, for example, with updating the Awesome Plugins page <https://github.com/planetjekyll/awesome-jekyll-plugins>.

**Comment by geraldb** [comment]
> Would be amazing to run those scripts as a part of a CI

There are two parts: Part I) Use the GitHub API for getting the statistics. Part II) That's the easy part for CI automation - using the "static" datafiles and readmes to update the jekyll pages / datafiles.

**Comment by markets** [comment]
> The files in /o (for output) get generated (auto-updated)

Maybe would be helpful to document this process, for example, in the README?

> you're more than welcome to join the planet jekyll org and help, for example, with updating the Awesome Plugins page 

Is this process also handled by the `yorobot/planetjekyll` script?

**Comment by geraldb** [comment]
> So, perhaps it's worth to run a manual update? most of data are actually outdated.
>
> Maybe would be helpful to document this process, for example, in the README?

I know. Here's my project list <https://github.com/yorobot/backup/blob/master/SUMMARY.md>. Sorry there's only so much I can do in a day (a month, a year).

**Comment by geraldb** [comment]
> Is this process algo handled by the yorobot/planetjekyll script?

Yes, but it was a long time ago :-).  A good start is <https://github.com/yorobot/planetjekyll/blob/master/script/genplugin.rb> - it reads the awesome readme and builds a datafile (in yaml) for the gems and categories for the next steps and so on.

**Comment by markets** [comment]
@geraldb I think would be very useful for potential contributors to document all these processes in each README's project. It would easier for the people to contribute. Now, you should run different scripts in different repos, so it's not clear to me what are the steps to help you updating these data :)

You built a lot of amazing organizations and projects here in GitHub, so thanks a lot for that! I'm just saying that more docs about this topic will probably help people contributing to these repos.

**Comment by geraldb** [comment]
Thanks for your kind words. No worries. The idea is to "gemify" the scripts first - it is / was a changing system (in development).  Still working on the first part, that is, the github statistics (see <https://github.com/gittiscripts>). Maybe one day it all comes together :-).

**Comment by markets** [comment]
Both, first and second part, would be very amazing tools, I'd like to use it for `Awesome Ruby` too :+1: 

Some time ago I started a similar project with a friend, he pushed a gist here: https://gist.github.com/AlexLarra/0ac306bfae319a940909. It converts an `awesome-*` like README to a YAML file.

**Comment by geraldb** [comment]
Keep going. That's a great idea. Big fan of "free form" text to "structured" data.  Another "try" even gemified :-) is the catalog.db, see <https://github.com/textkit/catalog.db/blob/master/lib/catalogdb/reader.rb>. I'm offline for today. All the best. Cheers. Greetings from Vienna.

**Pull request merged**
