### PR TITLE
Revamp site

### PR DESCRIPTION
**Pull request by ashmaroli**
WIP

### CODE REVIEW

**Comment by geraldb** [comment]
@ashmaroli  Thanks for your efforts.  Do you have a preview somewhere? What did you try to change? Might be a good idea to break up your changes into parts. For example,

- Polish/revamp the front page
- Polish/revamp the plugin pages (two pages - all and top)
- and so on

Not sure what you are trying to do here, for example? changing _data/o/plugins/plugins.yml → _data/plugins.yml
For your information - the plugins.yml gets auto-generated from the  awesome plugins readme, thus,  /o for output (auto-generated) folder and so on.
Also not sure if adding reset.css is worth it and so on.  Also note the "official" category for plugins will disapear (no need to add some if clauses and renames w/ liquid in the templates) - the offical category will become a tag (see the awesome plugin readme - not yet synched up with the page on the site). Cheers.

**Comment by ashmaroli** [comment]
> the plugins.yml gets auto-generated from the awesome plugins readme

I did figure that plugins.yml to be auto-generated.. just didnt know from where..  
Can that auto-generation be modified?

> Do you have a preview somewhere?

No.. not yet.. but will soon ( during the weekend ) have it on my fork. You may pull my branch and serve it locally if you can right now.

> Might be a good idea to break up your changes into parts

Sure. No probs. I assumed it to be better to view related changes in one commit.

**Comment by geraldb** [comment]
Again thanks for your efforts.

> I did figure that plugins.yml to be auto-generated.. just didnt know from where
>.Can that auto-generation be modified?

Yes. It can do anything ;-) - it is a ruby script (supposed to run daily or something, automatically - in the future someday), see <https://github.com/yorobot/planetjekyll/blob/master/script/genplugin.rb>

I would say focus on one thing first, that is, lets do it in small steps (if that works for you)  e.g. start with what is most important to you e.g. the plugins page? the front page? or something else?

**Comment by ashmaroli** [comment]
> I would say focus on one thing first, that is, lets do it in small steps

Its doable. :smiley: I'll move revamping the homepage to another PR

**Comment by geraldb** [comment]
Thanks for your understanding. 

I am all for using the new realtive_url and absolute_url filters in templates.  

As said before I am not so sure what reset.css adds - the idea is to keep the css (scss) simple / minimal. 

The list needs to get fixed - not sure what else you want to change (in the home page)?

**Comment by ashmaroli** [comment]
Preview links to leave feedback till I get the PRs in order..
Planet-home: [**Enter**](https://ashmaroli.github.io/planetjekyll.github.io/)
Planet-plugins: [**Enter**](https://ashmaroli.github.io/planetjekyll.github.io/plugins/)

**Comment by ashmaroli** [comment]
> I am not so sure what reset.css adds

`reset.css` [[source]](http://meyerweb.com/eric/tools/css/reset/reset.css) negates all browser-specific default styles allowing us fine-grain control over cross-browser styling

**Comment by geraldb** [comment]
Thanks for your efforts. Visuals is always a matter of taste, thus, I like some changes (but not others - sorry).

Great changes - +1 - lets do it:

I'd say lets for now work on the plugins pages (all n top):
* Active Tabs Marked (+1)

I'd say to avoid any disappointment on your side - I suggest creating new pages (templates) e.g. plugins2 and plugins2/top or something - and  keep  the old "classic" design (as is) and use the new "modern" design in parallel. I suggest that you "own" the new "modern" design (templates) and feel free to change as you please - the only thing the two designs share is the plugins.yml datafile.

**Comment by ashmaroli** [comment]
You're free to express your opinions without compromise &mdash; you need not worry if it would disappoint me. :smiley: 
Thank you for being polite in suggesting that I own a new set of templates, but unfortunately, I don't want to.. mostly because my idea depends on having to modify your *yorobot* plugin (and that would lead to inconsistent shared data)

I'm closing this PR now.
Feel free to use any of the proposed changes here when you get the time.

A

**Comment by geraldb** [comment]
> mostly because my idea depends on having to modify your yorobot plugin (and that would lead to inconsistent shared data)

What changes in the plugins.yml datafile do you want to see? I am happy to add your changes (if you're still interested). 

The idea always was (and still is) to share the (generated) plugins.yml from the aweseome plugins readme with everbody (including someday maybe the official plugin site -> https://github.com/jekyll/plugins ).  See -> http://talk.jekyllrb.com/t/awesome-jekyll-plugins-new-jekyll-plugin-community-directory-listing-started/2270/1 for a discussion. Cheers.  

PS: Again thanks for your effort and for trying. Some great ideas. I hope you will be back. Keep it up.

**Comment by ashmaroli** [comment]
:smiley: I've not left the project entirely.

the following should help you understand the changes in plugins.yml. The noteable change is to have a dedicated `key` for sub_categories (if they exist) and optionally to add a new line between every `array_item` for better human-readability:
```diff
    - gem: jekyll-sass-converter
      gem_url: https://rubygems.org/gems/jekyll-sass-converter
---   category: Official Plugins › Core / Built-in
+++   category: Official Plugins
+++   sub_category: Core / Built-in
      title: Sass Converter
      project_url: https://github.com/jekyll/jekyll-sass-converter
      descr: a Sass converter
      github: jekyll/jekyll-sass-converter
      created: 2014-01-26 00:42:50.000000000 Z
      updated: 2016-07-10 19:15:16.000000000 Z
      commit_msg: Don't need history sections. by Parker Moore
      stars: 54
      stars_week: 0
+++                                                                        
    - gem: jekyll-watch
      gem_url: https://rubygems.org/gems/jekyll-watch
---   category: Official Plugins › Core / Built-in
+++   category: Official Plugins
+++   sub_category: Core / Built-in
      title: Watch
      project_url: https://github.com/jekyll/jekyll-watch
      descr: rebuild your site when a file changes with the `--watch` switch
      github: jekyll/jekyll-watch
      created: 2014-06-26 22:41:48.000000000 Z
      updated: 2016-07-20 19:24:52.000000000 Z
      commit_msg: Release v1.5.0 by Parker Moore
      stars: 34
      stars_week: 0
+++                                                                        
    - gem: jekyll-feed
      gem_url: https://rubygems.org/gems/jekyll-feed
---   category: Official Plugins › Core / Optional
+++   category: Official Plugins
+++   sub_category: Core / Optional
      title: Feed
      project_url: https://github.com/jekyll/jekyll-feed
      descr: a plugin to generate an Atom (RSS-like) feed of your posts   **#GitHub Pages**
      github: jekyll/jekyll-feed
      created: 2015-05-12 13:28:32.000000000 Z
      updated: 2016-10-21 04:30:31.000000000 Z
      commit_msg: 'Update history to reflect merge of #143 [ci skip] by jekyllbot'
      stars: 244
      stars_week: 0
+++                                                                        
```
Optionally, if not needed anywhere else, the following changes as well:
- `commit_msg` key entirely.
- `stars_week`

**Comment by geraldb** [comment]
Good point about making the file more readable. Should be doable (as I said before I am offsite until the end of January e.g. hard to make "big" changes right now.)   

If you look at the latest version of <https://github.com/planetjekyll/awesome-jekyll-plugins>

There are no more subcatgories and the official category got removed. Instead you can now use tags (in addition to the category) e.g. #Official or #GitHub Pages etc.

stars_week is used for trending e.g. if plus than up and if negative than down; if 0 than nothing happened. 

commit_msg is the latest commit message from the plugin repo - how do you want to change it? 

Cheers.

**Pull request closed without merging**
